### ISSUE TITLE
Found problems in first run

### ISSUE THREAD

**Issue by KiralyCraft** [PentagonalCube/PickaxeConfigAssistant#1]
Hello there, first of all, i'd like to say this is an amazing tool. It works really great, however there are some flaws:

- Out of memory error does not stop the current session timer. If the miner crashed because of too much memory being allocated, it would still wait the --seconds specified, instead of jumping to the next set.

`Starting XMRig-nvidia with threads:50 blocks:50 (50x50)
{'mining_software': 'xmrig', 'gpu_type': 'nvidia'}
 * VERSIONS:     XMRig/2.4.2 libuv/1.14.1 CUDA/9.0 MSVC/2015
 * CPU:                 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (1) x64 AES-NI
 * GPU #1:       GeForce GTX 750 @ 1137/2505 MHz 50x50 12x25 arch:50 SMX:4
 * ALGO:         cryptonight, donate=1%
 * POOL #1:      pool.supportxmr.com:7777
 * COMMANDS:     'h' hashrate, 'e' health, 'p' pause, 'r' resume
[CUDA] Error gpu 1: <cryptonight_extra_cpu_init>:193 "out of memory"`

- Too many combinations cause the resulting graph to crash the program. I used the following command line: `main.py --index 1 --threads 10 --threadsmax 50 --threadsstep 4 --blocks 10 --blocksmax 50 --blocksstep 1 --seconds 20`

Everything went great until the final step:
`Traceback (most recent call last):
  File "D:\Auto-Clean Folder\New folder\main.py", line 151, in <module>
    main(sys.argv[1:])
  File "D:\Auto-Clean Folder\New folder\main.py", line 148, in main
    pca.save_graph()
  File "D:\Auto-Clean Folder\New folder\PickaxeConfigAssistant.py", line 498, in save_graph
    self.graph(self.generate_graph_data(), path)
  File "D:\Auto-Clean Folder\New folder\PickaxeConfigAssistant.py", line 624, in graph
    fig.savefig(file_name, facecolor=self.background_colour, transparent=True)
  File "C:\Users\KiralyCraft\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\KiralyCraft\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backend_bases.py", line 2259, in print_figure
    **kwargs)
  File "C:\Users\KiralyCraft\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 507, in print_png
    FigureCanvasAgg.draw(self)
  File "C:\Users\KiralyCraft\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 422, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "C:\Users\KiralyCraft\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 444, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "C:\Users\KiralyCraft\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 92, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: Image size of 124000x1200 pixels is too large. It must be less than 2^16 in each direction.`

**Comment by PentagonalCube** [comment]
Hi,

Many thanks for taking a look, your input is most appreciated. I'll get to work on these tonight and hopefully come up with solid solutions to the errors. 

At the moment the graphing is pretty coarse, so I'll get a look at that in more detail and try to make some improvements.

Cheers,
Louis

**Comment by PentagonalCube** [comment]
Moved this information into two new issues, closing this original issue for now.

- [#3 - Pickaxe Config Assistant attempts to create graph renders that are too large, matplotlib exception thrown](https://github.com/PentagonalCube/PickaxeConfigAssistant/issues/3)
- [#2 - If XMRig fails to start Pickaxe Config Assistant will still timeout awaiting the results of the benchmark](https://github.com/PentagonalCube/PickaxeConfigAssistant/issues/2)
